### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/releases#100]
# Monitoring

### Basic Stack Deployment

- [x] Create role in [metal-roles](https://github.com/metal-stack/metal-roles) (`control-plane/roles/monitoring`) and deploy to `monitoring` namespace
    - [x] Prometheus, Grafana and Alertmanager
        - [x] Alertmanager
            - [x] Allow configuration of rules and backends
            - [ ] Bring some useful default rules
        - [x] Grafana: Configurable Dashboards
            - [x] metal-api Dashboard
            - [x] Rethinkdb Dashboard
        - [x] Deploy Service Monitors
            - [x] metal-api
            - [x] masterdata-api
            - [x] masterdata-db (backup-restore-sidecar) / maybe add postgres-exporter as sidecar?
            - [x] metal-db (+ backup-restore-sidecar)
            - [x] ipam-db (backup-restore-sidecar) / maybe add postgres-exporter as sidecar?
            - [ ] gardener-metrics-exporter
    - [x] Thanos
        - [ ] Configurable Alerts for the Ruler
- [x] Create role in [metal-roles](https://github.com/metal-stack/metal-roles) (`control-plane/roles/logging`) and deploy to `monitoring` namespace
    - [x] Loki
    - [x] Promtail

### Control Plane Metrics Exporters

- [x] metal-metrics-exporter
    - [x] ~~Integrate into `metal-control-plane` helm-chart (https://github.com/metal-stack/helm-charts/tree/master/charts/metal-control-plane)~~ Added to monitoring role
- [x] rethinkdb-metrics-exporter
    - [x] ~~Integrate into [rethinkdb-backup-restore](https://github.com/metal-stack/metal-roles/tree/master/control-plane/roles/rethinkdb-backup-restore) role~~ Added to monitoring role
- [x] gardener-metrics-exporter
    - [x] Add deployment to `control-plane/roles/monitoring` role in metal-roles

### Discussions

- [ ] Thanos vs. Mimir
- [ ] Should we install a service mesh? (Linkerd)

## Partition

- [x] Create role in [metal-roles](https://github.com/metal-stack/metal-roles) (`partition/roles/monitoring`) and deploy to management server as [systemd service](https://github.com/metal-stack/ansible-common/tree/master/roles/systemd-docker-service) (wrapping a Docker container)
    - [x] Prometheus
        - [x] Scrape exporters
        - [ ] Scrape metal-image-cache-sync
    - [x] Exporters
        - [x] node_exporter
        - [x] ipmi_exporter
        - [x] blackbox_exporter
- [x] For the leaf switches
    - [x] Deploy exporters in the [leaf role](https://github.com/metal-stack/metal-roles/tree/master/partition/roles/leaf)
        - [x] frr_exporter
        - [x] cumulus_exporter
        - [x] node_exporter
        - [ ] metal-core
    - [x] Deploy promtail
- [x] For routers
    - [x] Deploy frr_exporter and node_exporter
    - [x] Deploy promtail

## Gardener Seeds

- [ ] Prometheus deployment
  - [ ] Service Monitors
    - [ ] lightbox_exporter
    - [ ] firewall node_exporter and nftables_exporter

## Overview

![monitoring](https://user-images.githubusercontent.com/15035165/207881960-6d97d596-25be-4950-a675-b12349a37c30.png)

**Comment by Gerrit91** [comment]
I guess the first version in place, so I close this issue. However, we want to move everything to a dedicated metal-monitoring repository and maybe also use some different deployment strategies than before.
