### ISSUE TITLE
SONiC Support

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/releases#76]
- [x] Sample repository with Containerlab (2 spine + 2 leaf topology + 2 machines) --> communication between 2 machines is possible through EVPN overlay network
  - [x] Deciding for SONiC distro (Edgecore / Broadcom / Vanilla)
- [x] Migration of current Cumulus configuration to equivalent SONiC configuration 
- [x] Implementation into metal-stack
  - [ ] Adapt mini-lab (metal-core, deployment playbooks)

**Comment by robertvolkmann** [comment]
Sample repository: https://github.com/robertvolkmann/sonic-poc

**Comment by robertvolkmann** [comment]
Points for further investigation:
* Default tx-interval for lldp is 30 seconds and can only be changed via lldpcli. [https://github.com/Azure/sonic-buildimage/blob/202111/dockers/docker-lldp/lldpd.conf.j2](lldpd.conf.j2)
* Setting `configure lldp portidsubtype macaddress` via lldpcli has not the desired effect:
`
2022-06-08T11:46:01.326Z	debug	lldp	{"detectedNeighbor": "Name:mini-lab-leaf02 Desc:SONiC Software Version: SONiC.HEAD.0-dirty-20220603.064718 - HwSku: Force10-S6000 - Distribution: Debian 11.3 - Kernel: 5.10.0-8-2-amd64 Chassis:Mac:a2:85:c9:17:52:9c Port::"}
`

**Comment by robertvolkmann** [comment]
`lldpgrmd` reacts on changes in the Redis database and configured the `portidsubtype` to `local`. It used the `alias` field from the `PORT` definitions.
https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-lldp/lldpmgrd#L145

**Comment by robertvolkmann** [comment]
We can use `config replace <file>` in `metal-core` to reload the whole configuration, but it works only for versions of SONiC that contains [SONiC Yang support for VXLAN](https://github.com/Azure/sonic-buildimage/pull/7294).

**Comment by Gerrit91** [comment]
Support for SONiC was release in metal-stack v0.14.0.
